services:
  app:
    build: .
    ports:
      - "4001:80"
    restart: unless-stopped
    networks:
      - qualifylead_net

networks:
  qualifylead_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
